repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: trailing-whitespace

-   repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.2
    hooks:
    -   id: gitlab-ci-linter
        args:
        - '--server'
        - 'https://gitlab.praktikum-services.ru'
        - '--project'
        - 'anton-alekseyev/sausage-store'
        - '--private-token'
        - 'W2wVw-hJNo89hMEg_FRQ'
