stages:
  - build
  - test
  - release
  - deploy
include:
  - template: Security/SAST.gitlab-ci.yml
  - local: /template.gitlab-ci.yml

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  #JAVA_OPTS: -XX:MaxRAMPercentage=90
  SAST_EXCLUDED_ANALYZERS: "eslint,nodejs-scan-sast"

cache: &global_cache
  key: maven
  paths:
    - .m2/repository

build-code-job: # задача с именем build-code-job
  stage: build   # этап build
  cache:
    <<: *global_cache
  script: # объявление скрипта
    - cd backend
    - mvn package -Dversion.application=${VERSION} -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
#  artifacts:
#      paths:
#        - sausage-store-${VERSION}/sausage-store-${VERSION}.jar # сохранение собранного бэкенда как артефакт
#        - ${CI_PROJECT_DIR}/.m2/ # сохранение зависимостей для SAST

spotbugs-sast:
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  variables:
    COMPILE: "false"
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  script:
    - cd backend
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN}
      -Dsonar.projectName=${SONAR_PROJECT_NAME_BACK}

upload-release: # задача с именем upload-release
  stage: release # этап release
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd backend
    - NEXUS_ENCODE_PASSWORD=$(echo $NEXUS_REPO_PASS | base64 -d)
    - mvn -s settings.xml deploy -DskipTests -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -Dversion.application=${VERSION} -Dnexus.password=${NEXUS_ENCODE_PASSWORD}
    - |
      DATA=$(cat <<EOF
      {"blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Вышла новая версия сосисочной :pepe-exhausted: — $VERSION from $GITLAB_USER_LOGIN.\nСкачать бекенд можно по ссылке"
                        },
                        "accessory": {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "Backend",
                                "emoji": true
                            },
                            "value": "Frontend",
                            "url": "${NEXUS_REPO_BACKEND_URL}/com/yandex/practicum/devops/sausage-store/$VERSION/sausage-store-$VERSION.jar",
                            "action_id": "button-action"
                        }
                    }
                ]
               }
      EOF
      )
      curl -X POST -H "Content-type: application/json" --data "$DATA" ${NOTIFY_SLACK_URL}

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - when: always
  extends: .ssh-connection
  environment:
    name: staging
    url: http://$DEV_HOST:$DEV_APP_PORT
  script:
    - scp ./backend/sausage-store-backend.service ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/sausage-store-backend.service
    - ssh ${DEV_USER}@${DEV_HOST} "export "CURRENT_VERSION=${VERSION}"; export "VERSION=${VERSION}"; export "DEV_HOST=${DEV_HOST}";export "NEXUS_REPO_BACKEND_URL=${NEXUS_REPO_BACKEND_URL}"; export "NEXUS_REPO_USER=${NEXUS_REPO_USER}"; export "NEXUS_REPO_PASS=$NEXUS_REPO_PASS";setsid /bin/bash -s " < ./backend/deploy.sh