stages:
  - build
  - test
  - release
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - local: /template.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  #JAVA_OPTS: -XX:MaxRAMPercentage=90
  SAST_EXCLUDED_ANALYZERS: "eslint,nodejs-scan-sast"

cache: &global_cache
  key: maven
  paths:
    - .m2/repository


build-docker-kaniko:
  stage: build
  cache: [ ]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  extends: .docker-registry-auth
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend-report"
      --dockerfile "${CI_PROJECT_DIR}/backend-report/Dockerfile"
      --cache-copy-layers
      --destination "${CI_REGISTRY_IMAGE}/${DOCKER_BACKEND_REPORT_NAME}:${VERSION}"
      --cache=true

build-code-job: # задача с именем build-code-job
  stage: build   # этап build
  cache:
    <<: *global_cache
  script: # объявление скрипта
    - cd backend-report
    - mvn package -Dversion.application=${VERSION} -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository

spotbugs-sast:
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  variables:
    COMPILE: "false"
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository

.sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  cache: [ ]
  script:
    - cd backend-report
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK_REPORT}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN}
      -Dsonar.projectName=${SONAR_PROJECT_NAME_BACK_REPORT}

upload-docker-latest:
  variables:
    GIT_STRATEGY: none
  #image: docker:20.10.12-dind-rootless
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/$DOCKER_BACKEND_REPORT_NAME:$VERSION latest

deploy-docker-compose:
  stage: deploy
  cache: [ ]
  image: docker:20.10.12-dind
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - when: on_success
  extends: .docker-compose-init
  script:
    - docker-compose --context sausage-store up -d backend-report
    - docker --context sausage-store ps